name: ReDoc
on:
  push:
    branches: [main]
jobs:
  bundle:
    runs-on: ubuntu-latest
    name: bundle
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: redoc-cli 
        uses: seeebiii/redoc-cli-github-action@v9
        with:
          args: 'bundle 2fauth-0.1.0.yaml -o docs/index.html'