name: ReDoc
on:
  push:
    branches: [main]
jobs:
  bundle:
    runs-on: ubuntu-latest
    name: bundle
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install tool to add code snippets
      - name: Install snippet-enricher-cli
        run: npm install snippet-enricher-cli

      # Run tool to add code snippets
      - name: Run snippet-enricher-cli
        run: npx snippet-enricher-cli --input=OpenAPI/maintenance-api.yaml --targets="shell_curl,node_native,python_python3" > openapi-with-examples.json

      # use redoc-cli-github-action to generate your HTML bundle
      - name: redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle 2fauth-0.1.0.yaml -o docs/index.html'